language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t runzeliu29/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true runzeliu29/docker-react npm run test